In [1]:
import numpy as np

#Nível Fácil

Exercício 1: Dado o array Y = np.array([10, 20, 30, 40, 50, 60]), extraia os últimos 3 elementos.

Exercício 2: Dado o array Z = np.array([100, 200, 300, 400, 500]), selecione o segundo e o quarto elemento.

Exercício 3: Dado o array W = np.array(['x', 'y', 'z', 'a', 'b', 'c']), inverta a ordem dos elementos, e depois selecione apenas os elementos nas posições pares.

In [ ]:
Y = np.array([10, 20, 30, 40, 50, 60])
Y[-3:]

array([40, 50, 60])

In [ ]:
Z = np.array([100, 200, 300, 400, 500])
Z[1::2]

array([200, 400])

In [ ]:
Z[[1,3]]

array([200, 400])

In [38]:
W = np.array(['x', 'y', 'z', 'a', 'b', 'c'])
W

array(['x', 'y', 'z', 'a', 'b', 'c'], dtype='<U1')

In [39]:
W[::-1][::2]

array(['c', 'a', 'y'], dtype='<U1')

In [ ]:
W[[0,2,4]]

array(['c', 'a', 'y'], dtype='<U1')

#Nível Intermediário

Exercício 4: Dada a matriz M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), selecione a segunda coluna.

Exercício 5: Dada a matriz N = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]]), selecione a última linha.

Exercício 6: Dada a matriz P = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]), selecione o bloco 2x2 que começa na posição (1, 2).

In [ ]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
M[:, 1]

array([2, 5, 8])

In [ ]:
N = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
N

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [ ]:
N[2,:]

array([ 90, 100, 110, 120])

In [ ]:
N[-1,:]

array([ 90, 100, 110, 120])

In [ ]:
P = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
P

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
P[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

#Nível Difícil

Exercício 7: Dada a matriz Q = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]]), selecione todos os elementos das linhas ímpares e colunas pares.

Exercício 8: Dada a matriz R = np.array([[5, 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]]), extraia uma submatriz 2x3 que começa na posição (2, 1).

Exercício 9: Dado o array tridimensional T = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]), selecione o segundo "plano" (subarray bidimensional) completo.

Exercício 10: Dada a matriz U = np.array([[20, 30, 40], [50, 60, 70], [80, 90, 100]]), inverta tanto as linhas quanto as colunas.

In [ ]:
 Q = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])
 Q

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [ ]:
Q[1::2,::2]

array([[ 50,  70],
       [130, 150]])

In [ ]:
R = np.array([[5, 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]])
R

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100]])

In [ ]:
R[2:4, 1:4]

array([[60, 65, 70],
       [85, 90, 95]])

In [ ]:
T = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
T

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
T[1]

array([[5, 6],
       [7, 8]])

In [ ]:
U = np.array([[20, 30, 40], [50, 60, 70], [80, 90, 100]])
U

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [ ]:
U[::-1, ::-1]

array([[100,  90,  80],
       [ 70,  60,  50],
       [ 40,  30,  20]])

#Nível Difícil

Exercício 1:
Dado o array A = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50]), selecione todos os elementos, exceto o primeiro e o último, mas na ordem inversa.

Exercício 2:
Dado o array B = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]), selecione a diagonal principal.

Exercício 3:
Dado o array C = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17], [19, 21, 23], [25, 27, 29]]), selecione os elementos das duas últimas linhas e das duas primeiras colunas.

Exercício 4:
Dado o array D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]], [[13, 14], [15, 16]]]), selecione todos os elementos na última "plana" (a última matriz bidimensional) e inverta as linhas e colunas.

Exercício 5:
Dado o array E = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]]), selecione o bloco 2x2 do centro da matriz.

Exercício 6:
Dado o array F = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]), reestruture-o em uma matriz 3x4 e depois selecione a segunda coluna de cada uma das duas primeiras linhas.

Exercício 7:
Dado o array G = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]]), selecione todos os elementos, exceto aqueles na borda da matriz.

Exercício 8:
Dado o array H = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]), selecione o segundo elemento de cada "plano" (subarray bidimensional) e inverta a ordem dos subarrays.

Exercício 9:
Dado o array I = np.array([[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24], [26, 28, 30, 32]]), selecione os elementos das duas primeiras linhas e das colunas pares.

Exercício 10:
Dado o array J = np.array([[[5, 10], [15, 20], [25, 30]], [[35, 40], [45, 50], [55, 60]], [[65, 70], [75, 80], [85, 90]]]), selecione o terceiro elemento de cada "linha" de cada "plano" e reestruture a saída em uma matriz 3x2.

In [19]:
 # 1 selecione todos os elementos, exceto o primeiro e o último, mas na ordem inversa
 A = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
A[::-1]
A[1:-1][::-1]

array([45, 40, 35, 30, 25, 20, 15, 10])

In [20]:
# 2 selecione a diagonal principal
B = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
np.shape(B)

(5, 5)

In [27]:
np.arange(B.shape[0])

array([0, 1, 2, 3, 4])

In [28]:
B[np.arange(B.shape[0])]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
B[np.arange(B.shape[0]), np.arange(B.shape[0])]

array([ 1,  7, 13, 19, 25])

In [29]:
np.diag(B)

array([ 1,  7, 13, 19, 25])

In [32]:
# 3 selecione os elementos das duas últimas linhas e das duas primeiras colunas
C = np.array([[1, 3, 5], [7, 9, 11], [13, 15, 17], [19, 21, 23], [25, 27, 29]])
C

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [36]:
C[-2:,:2]

array([[19, 21],
       [25, 27]])

In [40]:
# 4 selecione todos os elementos na última "plana" (a última matriz bidimensional) e inverta as linhas e colunas
D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]], [[13, 14], [15, 16]]])
D

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [41]:
D[-1:]

array([[[13, 14],
        [15, 16]]])

In [42]:
D[-1:, ::-1, ::-1]

array([[[16, 15],
        [14, 13]]])

In [43]:
# 5 selecione o bloco 2x2 do centro da matriz
E = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120], [130, 140, 150, 160]])
E

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [45]:
E[1:3,1:3]

array([[ 60,  70],
       [100, 110]])

In [48]:
# 6 reestruture-o em uma matriz 3x4 e depois selecione a segunda coluna de cada uma das duas primeiras linhas
F = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
F

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
F2 = F.reshape(3,4)
F2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
F2[:2,1]

array([2, 6])

In [56]:
# 7 selecione todos os elementos, exceto aqueles na borda da matriz
G = np.array([[100, 200, 300], [400, 500, 600], [700, 800, 900]])
G

array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])

In [57]:
G[1,1]

500

In [60]:
G[1:2,1:2]

array([[500]])

In [61]:
# 8 selecione o segundo elemento de cada "plano" (subarray bidimensional) e inverta a ordem dos subarrays
H = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
H

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [63]:
H[:,:,1]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [64]:
H[:,:,1][::-1]

array([[20, 23, 26],
       [11, 14, 17],
       [ 2,  5,  8]])

In [65]:
# 9 selecione os elementos das duas primeiras linhas e das colunas pares
I = np.array([[2, 4, 6, 8], [10, 12, 14, 16], [18, 20, 22, 24], [26, 28, 30, 32]])
I

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [75]:
I[:2]

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [76]:
I[0, 1::2]

array([4, 8])

In [79]:
I[:2, ::2]

array([[ 2,  6],
       [10, 14]])

In [80]:
# 10 selecione o terceiro elemento de cada "linha" de cada "plano" e reestruture a saída em uma matriz 3x2.
J = np.array([[[5, 10], [15, 20], [25, 30]], [[35, 40], [45, 50], [55, 60]], [[65, 70], [75, 80], [85, 90]]])
J

array([[[ 5, 10],
        [15, 20],
        [25, 30]],

       [[35, 40],
        [45, 50],
        [55, 60]],

       [[65, 70],
        [75, 80],
        [85, 90]]])